iterative/scmrepo

scmrepo/progress.py

fixes https://github.com/iterative/scmrepo/issues/16

progress: change ascii decoding to utf-8 for localized languages in dulwich backend

---

.pre-commit-config.yaml

pinning `bandit` version to 1.7.2 because of the broken of flake8-bandit

---

setup.cfg

Release a new version of scmrepo

---

scmrepo/fs.py
tests/test_fs.py
tests/test_git.py

This reverts commit 42db9e4754d45f21ff93d5d8ed96fc4eb7f42801 and 29d834163ca6c5aa60be6f0f68785e3c2f6f2f87.
To unblock https://github.com/iterative/dvc/pull/7435 and https://github.com/iterative/dvc/pull/7245.

Revert #24 and #25

---

scmrepo/git/__init__.py
scmrepo/git/backend/base.py
scmrepo/git/backend/dulwich/__init__.py
scmrepo/git/backend/gitpython.py
scmrepo/git/backend/pygit2.py
tests/test_git.py

re-adds some needed clone/fetch changes from https://github.com/iterative/dvc/pull/5624 that were dropped by mistake after moving to scmrepo and waiting for upstream clone changes

git: implement fetch

---

scmrepo/git/backend/dulwich/__init__.py
tests/test_git.py

see https://github.com/iterative/dvc/runs/5597238590?check_suite_focus=true

[WIP] dulwich: fix clone with `file://` protocol on windows

---

scmrepo/git/__init__.py
scmrepo/git/backend/pygit2.py
tests/test_git.py

see https://github.com/iterative/dvc/runs/5748917747?check_suite_focus=true

git: fix backend reorder bugs

---

scmrepo/fs.py
tests/test_fs.py

fsspec requires it to return a list of infos, not a dict.

gitfs: ls: fix return value if detail=True

---

scmrepo/git/__init__.py

Closes https://github.com/iterative/dvc/issues/7700

Fix windows `install_hook`

---

tests/test_git.py

- add test for `iter-remote-refs` refs (broken for `dulwich<0.20.38`)
- bump dulwich version to `>=0.20.38`
Related https://github.com/iterative/dvc/issues/7670

tests: add iter-remote-refs test

---

.github/workflows/release.yaml
.github/workflows/tests.yaml
pyproject.toml
setup.cfg

This way we can release in the same way we do in dvc, dvc-data and dvc-objects, by just creating the release, no manual bumping required.

use setuptools_scm

---

scmrepo/git/backend/dulwich/__init__.py
scmrepo/git/backend/pygit2.py

Was discovered as a part of https://github.com/iterative/dvc/issues/7824

objects: don't recompute object size

---

scmrepo/git/backend/pygit2.py

pygit2: use obj.size for blobs

---

src/scmrepo/git/backend/dulwich/__init__.py
src/scmrepo/git/backend/dulwich/client.py
src/scmrepo/git/backend/dulwich/credentials.py

Temporary patch while waiting for https://github.com/jelmer/dulwich/pull/976

dulwich: add support for git credential helpers

---

src/scmrepo/exceptions.py
src/scmrepo/git/backend/dulwich/__init__.py
src/scmrepo/git/backend/dulwich/asyncssh_vendor.py

- exceptions: update AuthError message
- dulwich: add AuthError on HTTPUnauthorized
fixes iterative/dvc#8654

improve auth error on clone

---

.github/workflows/tests.yaml
tests/docker-compose.yml
tests/test_stash.py

Forgot to include the test in #182

tests: Add `test_git_stash_workspace_reinstate_index`

---

setup.cfg
src/scmrepo/git/backend/dulwich/credentials.py

It was released on 0.20.49. See https://github.com/jelmer/dulwich/pull/1079.
cc @dtrifiro

credentials: remove upstreamed url matching functions

---

src/scmrepo/git/__init__.py
src/scmrepo/git/backend/dulwich/client.py
src/scmrepo/git/credentials.py

Till we get time to implement #190.

fetch_refspecs: drop to dulwich if cred-helper is set

---

src/scmrepo/fs.py

While waiting for https://github.com/fsspec/filesystem_spec/pull/1191

fs: temporary implement get_file

---

src/scmrepo/git/backend/dulwich/client.py
src/scmrepo/git/credentials.py

- Adds higher level `git.credentials` API equivalent to `git-credentials`
- `scmrepo` clients should use `Credential.fill/approve/reject` rather than using `Helper.get/store/erase` directly (as described in https://git-scm.com/docs/git-credential#_typical_use_of_git_credential)
- Microsoft's GCM now fully supported
- Currently only used in dulwich backend for HTTP clients
- Credentials that are successfully filled by helper backend will be approved/stored upon a successful request
Closes #215

git.credentials: implement full fill/approve/reject workflow

---

src/scmrepo/git/__init__.py
src/scmrepo/git/backend/dulwich/client.py
src/scmrepo/git/backend/pygit2/callbacks.py
src/scmrepo/git/credentials.py

credentials: cache interactive credentials in memory

---

src/scmrepo/git/credentials.py
tests/test_credentials.py

credentials: generalize prompt behavior

---

src/scmrepo/git/backend/dulwich/__init__.py
src/scmrepo/git/backend/dulwich/client.py

- Ensures that request body is re-used when retrying requests due to auth reasons
Fixes https://github.com/iterative/dvc/issues/9290
This also fixes a separate issue where `exp remove` would report that it succeeded even if the git remote rejected the remove. (`exp remove` will not work in codespaces, as the github token generated for a codespace does not have delete permissions)

dulwich: preserve data from generators when retrying request

---

src/scmrepo/git/backend/base.py
src/scmrepo/git/backend/dulwich/__init__.py
src/scmrepo/git/backend/gitpython.py
src/scmrepo/git/backend/pygit2/__init__.py
tests/test_git.py

NOTE: this is a breaking change and requires scmrepo major version bump
Closes #123

git: change default add behavior to add(force=False)

---

src/scmrepo/git/backend/dulwich/__init__.py

Fixes https://github.com/iterative/dvc/issues/9290

dulwich: use repo.generate_pack_data wrapper

---

setup.cfg
src/scmrepo/git/backend/dulwich/__init__.py

Closes https://github.com/iterative/dvc/issues/9262

dulwich: bump minver to 0.21.5

---

src/scmrepo/git/backend/dulwich/__init__.py

discord context: https://discord.com/channels/485586884165107732/1121703959632031764

dulwich: check if ssh is in path before preferring over asyncssh

---

src/scmrepo/git/__init__.py
src/scmrepo/git/backend/base.py
src/scmrepo/git/backend/dulwich/__init__.py
src/scmrepo/git/backend/gitpython.py
src/scmrepo/git/backend/pygit2/__init__.py
src/scmrepo/git/objects.py

adds more prerequisites from GTO around annotated tag behavior

git: implement remaining gto tag functions

---

src/scmrepo/git/__init__.py
src/scmrepo/git/backend/gitpython.py

see: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=766627&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3

gitpython: raise NotImplementedError when import fails

---

setup.cfg

deps: bump dulwich minver to 0.21.6

---

src/scmrepo/git/backend/base.py
src/scmrepo/git/backend/pygit2/__init__.py
src/scmrepo/git/backend/pygit2/callbacks.py
tests/test_pygit2.py

pygit2: use update_tip callbacks instead of temp remote refspecs

---

src/scmrepo/git/__init__.py
src/scmrepo/git/backend/base.py
src/scmrepo/git/backend/dulwich/__init__.py
src/scmrepo/git/backend/gitpython.py
src/scmrepo/git/backend/pygit2/__init__.py
src/scmrepo/git/config.py
tests/test_git.py

prerequisites for https://github.com/iterative/scmrepo/pull/278

git: add generic backend implementation for reading git config

---

pyproject.toml
src/scmrepo/fs.py

https://github.com/iterative/dvc-objects/pull/262

deps: update dvc-objects to >=3

---

src/scmrepo/git/lfs/client.py

I've refactored the LFS auth logic a bit such that _only_ Batch API requests might be made &ndash; if necessary &ndash; with the user's Git credentials while LFS object download requests _never_ include these credentials for authentication, as the Batch API response will contain auth information in the `header` property which is included in the LFS object requests already. Thus, applying the previous `@_authed` decorator to the `LFSClient._download()` method was essentially a no-op because the unauthenticated request (w.r.t. the `@_authed` decorator) always succeeded because of the credentials included in the header.
The change also includes two fixes w.r.t. attempting an unauthenticated request to the Batch API first and adding Git credentials if the first request fails with HTTP status …

lfs: authenticate with Git credentials only to Batch API requests

---

pyproject.toml

Revert "build(deps-dev): bump pytest-cov from 3.0.0 to 4.1.0"

---

pyproject.toml
tests/conftest.py

Replaces https://github.com/iterative/scmrepo/pull/323

chore(deps): bump pytest-asyncio

---

pyproject.toml
tests/test_dulwich.py
tests/vendor/test_paramiko_vendor.py

Related to this https://github.com/iterative/dvc/issues/10395

fix(deps): use the latest dulwich

---

src/scmrepo/git/backend/pygit2/__init__.py

This was deprecated in 1.14.0. See https://github.com/libgit2/pygit2/blob/facaf22db399c6ec429df62f827d37f11a6472e6/CHANGELOG.md?plain=1#L114.

replace deprecated `GIT_*` constants with `pygit2.enums`

---

tests/docker-compose.yml

Closes https://github.com/iterative/scmrepo/issues/187.

unpin docker image

---

src/scmrepo/git/backend/dulwich/__init__.py
src/scmrepo/git/backend/pygit2/__init__.py
tests/test_git.py

Revert "git: implement list_all_commits using pygit2"

---

src/scmrepo/git/backend/dulwich/__init__.py
src/scmrepo/git/backend/pygit2/__init__.py
tests/test_git.py

git: implement list_all_commits using pygit2

---

pyproject.toml
src/scmrepo/git/backend/dulwich/__init__.py
tests/test_git.py

Fixed upstream: https://github.com/jelmer/dulwich/pull/1728.

unskip test_ignored_dir_unignored_subdirs test
