.coveragerc, .github/workflows/tests.yaml, pyproject.toml, scmrepo/git/__init__.py, scmrepo/git/backend/base.py, scmrepo/git/backend/dulwich/__init__.py, scmrepo/git/backend/gitpython.py, scmrepo/git/backend/pygit2.py, setup.cfg, tests/conftest.py, tests/test_dulwich.py, tests/test_git.py, tests/test_pygit2.py, tests/test_scmrepo.py
Migrating https://github.com/iterative/dvc/blob/004e15c2c00a24c7a8fba88611def600a9dd223f/tests/unit/scm/test_git.py.
=> add tests - part 1

scmrepo/git/backend/dulwich/asyncssh_vendor.py
Should fix https://github.com/iterative/dvc/issues/7085
=> dulwich: fall back to OpenSSH host config username/pw in asyncssh vendor

scmrepo/git/__init__.py, scmrepo/git/backend/base.py, scmrepo/git/backend/dulwich/__init__.py, scmrepo/git/backend/gitpython.py, scmrepo/git/backend/pygit2.py, tests/test_git.py
fix: #4 and https://github.com/iterative/dvc/issues/6051
In dvc we get a random toggling branch name in `exp show`. It is because
when we iter branches the `dulwich.refs.keys` gives an unordered `Set`
of refs. Here we reordered it, and makes current active branch always be
in the first order.
1. Add order to the result of dulwich.refs.keys.
2. Make active branch always in the first place.
3. Add a new test to it.
=> dulwich: fix output of `describe`(#4)

scmrepo/git/backend/dulwich/__init__.py, scmrepo/git/backend/pygit2.py, tests/test_dulwich.py, tests/test_git.py
Fixes `get_ref` for annotated tags.
Closes iterative/dvc#6383
From https://github.com/iterative/dvc/pull/7008
=> `get_ref`: Fix annotated tags

scmrepo/fs.py, tests/test_fs.py
This PR makes our fs accept paths relative to the root of the repo and using / as a separator.
Previous behaviour was a legacy from old dvc.
Pre-requisite for making dvcfs/repofs/etc switch to the same relative repo paths and / separators.
=> fs: detach from local filesystem

scmrepo/fs.py, tests/test_fs.py, tests/test_git.py
fsspec filesystems don't yet have a notion of cwd, so "." should not be used.
Instead, we should support using fs.root_marker ("" in our case), which is
currently broken.
=> fs: support root_marker

scmrepo/git/backend/pygit2.py, tests/test_git.py
When we were converting windows path to posixpath, the values
were not in effect because we were not setting it to the
variable.
Also fixes #11, which unskips  on Windows + pygit2 backend, which
was due to the above bug.
=> pygit2: fix posixpath conversion from windows on is_ignored

scmrepo/git/__init__.py, scmrepo/git/backend/base.py, scmrepo/git/backend/dulwich/__init__.py, scmrepo/git/backend/gitpython.py, scmrepo/git/backend/pygit2.py, setup.cfg, tests/test_git.py, tests/test_scmrepo.py
- Moves `Git.clone(rev=...)` checkout handling out of backend `clone()` and into `Git.clone()`. Separating this behavior allows us to use `clone()` from one backend and `checkout()` from another, since some backends may implement one but not the other.
- Implements clone in dulwich backend ~~(pending fix for https://github.com/dulwich/dulwich/issues/920)~~
- Implements clone in pygit backend (shallow clone not supported)
Will close https://github.com/iterative/dvc/issues/2215
=> dulwich/pygit: implement backend clone

scmrepo/git/backend/dulwich/asyncssh_vendor.py, setup.cfg, tests/conftest.py, tests/test_git.py
Will close https://github.com/iterative/scmrepo/issues/43
=> asyncssh: loosen upper version limit

setup.cfg
In version 1.5.0, I got a 
> ImportError: cannot import name 'GIT_MERGE_PREFERENCE_FASTFORWARD_ONLY' from 'pygit2'
`GIT_MERGE_PREFERENCE_FASTFORWARD_ONLY` was introduced in 1.6.0. Upgrade the min version of `pygit2` to fix it.
=> Solve `pygit2` version conflict

scmrepo/git/__init__.py
- When selecting a backend to use for a given git call, we will now try the most recently used backend first, before trying the remaining backends
- If we are switching backends, close the previously used backend before making the git call w/new backend
Should fix https://github.com/iterative/dvc/issues/7458
=> git: reuse most recent backend when possible

scmrepo/git/backend/dulwich/asyncssh_vendor.py, setup.cfg, tests/test_dulwich.py
Dulwich expects the underlying SSH vendor to handle partial reads, when dulwich calls `read` with a specific length `n`, it expects the git server to return exactly that many bytes (it does not use `n` as a generic max read buffer size). In our asyncssh vendor if dulwich requests `n` bytes, we need to continue reading until the server has sent all the expected data.
Will fix https://github.com/iterative/dvc/issues/7361
Will fix https://github.com/iterative/dvc/issues/7537
=> dulwich: account for partial pkt reads in asyncssh vendor

scmrepo/git/__init__.py, scmrepo/git/backend/base.py, scmrepo/git/backend/dulwich/__init__.py, scmrepo/git/backend/gitpython.py, scmrepo/git/backend/pygit2.py, tests/test_git.py
fix: #58
1. Unify the API of `push_refspec` and  `fetch_refspec`.
2. Can push multi `refspec` for one time.
3. No repository Error handle for `fetch_refspec`
4. Now the `push_refspec` and  `fetch_refspec` will return the status for each refspec.
=> Update on push_refspec and fetch_refspec (#58)

scmrepo/fs.py, scmrepo/git/backend/pygit2.py, scmrepo/git/objects.py, tests/test_fs.py, tests/test_git.py
=> gitfs: better comply with fsspec

setup.cfg
Tests on windows with python 3.10 result in:
```
___________________ ERROR collecting tests/test_dulwich.py ____________________
ImportError while importing test module 'D:\a\scmrepo\scmrepo\tests\test_dulwich.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\hostedtoolcache\windows\Python\3.10.4\x64\lib\importlib\__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests\test_dulwich.py:7: in <module>
import paramiko
.nox\tests-3-10\lib\site-packages\paramiko\__init__.py:22: in <module>
from paramiko.transport import SecurityOptions, Transport
.nox\tests-3-10\lib\site-packages\paramiko\transport.py:89: in <module>
from paramiko.dsskey import DSSKey
.nox\tests-3-10\lib\site-packages\paramiko\dsskey.py:37: in …
```
=> tests: bump paramiko to 2.10.0

scmrepo/git/backend/dulwich/__init__.py, setup.cfg
dulwich 0.20.37 updated type hints for `fetch` (see https://github.com/jelmer/dulwich/pull/957)
fixes #65
=> dulwich: update fetch_refspecs for dulwich 0.20.37

scmrepo/git/backend/base.py, scmrepo/git/backend/dulwich/__init__.py, scmrepo/git/backend/gitpython.py, scmrepo/git/backend/pygit2.py, tests/test_git.py
note that `untracked_files` is only currently available in `dulwich>=0.20.38`
=> git: add untracked_files kwarg to status

scmrepo/git/backend/dulwich/__init__.py, tests/test_git.py
This will speed up calling `is_dirty` when `untracked_files=False`
related to #69
=> dulwich: use untracked_files="no" in is_dirty

scmrepo/fs.py, scmrepo/git/objects.py, scmrepo/utils.py
We are effectively reading every object in the tree that we parse right now,
which takes a very long time.
Before fsspec migration, we used to not use info/size during walking at all.
Cuts down `dvc exp show -A` time for me from ~50sec down to ~3sec.
Related iterative/dvc#7824
=> fs: compute size lazily

scmrepo/git/backend/base.py, scmrepo/git/backend/dulwich/__init__.py, scmrepo/git/backend/gitpython.py, scmrepo/git/backend/pygit2.py, scmrepo/git/stash.py, tests/test_pygit2.py, tests/test_stash.py
Adds support for `--index` and force-applying in `stash apply`
prereq for https://github.com/iterative/dvc/issues/6930
=> stash apply: support reinstate_index and skip_conflicts

scmrepo/git/backend/dulwich/__init__.py, scmrepo/git/backend/pygit2.py, setup.cfg, tests/test_git.py
- bump pygit2 to 1.10.0
- force dulwich.status to return posix-style paths for untracked files
=> pygit2: implement status

src/scmrepo/git/backend/dulwich/__init__.py
related: https://github.com/iterative/example-repos-dev/pull/141
=> dulwich: reraise porcelain.Error when using porcelain methods

src/scmrepo/git/__init__.py, src/scmrepo/git/backend/base.py, src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/gitpython.py, src/scmrepo/git/backend/pygit2.py, tests/test_git.py
fix: #144
In our current describe function we only accept one rev at a time and will try to get a reference for every reference in the repo. It will cost O(MN) in the `exp show` in which we try to get a ref for every single experiment.
=> Add mutli rev support for function `describe`

src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/pygit2.py
workaround for https://github.com/iterative/scmrepo/issues/148
=> codespaces: try codespaces system config if we can't get committer identity

.pre-commit-config.yaml, pyproject.toml, src/scmrepo/git/backend/dulwich/credentials.py, src/scmrepo/git/backend/pygit2.py
See https://github.com/PyCQA/bandit.
=> add bandit, a security linter

src/scmrepo/git/backend/dulwich/__init__.py, tests/test_git.py
fix: #154
1. Wrap KeyError from fetch_refspec into SCMError.
2. Modify the test to test this change.
=> Wrap  KeyError from fetch_refspec into SCMError.

src/scmrepo/git/backend/dulwich/__init__.py
Closes #160
When `GIT_SSH_COMMAND` or `GIT_SSH` are set, use the specified command (via dulwich's subprocess vendor) instead of our asyncssh vendor.
=> dulwich: use GIT_SSH_COMMAND when set

setup.cfg
Related to https://github.com/iterative/dvc/issues/8217
Need to release the `pathspec` requirement here.
=> Release pathspec requirement.

src/scmrepo/git/backend/base.py, src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/gitpython.py, src/scmrepo/git/backend/pygit2.py
adds dummy implementation for `pygit2` and `gitpython`
In some cases, switching backends (from dulwich) would result in `AttributeNotFoundError` due to missing implementation in `pygit2` and `gitpython`.
=> add check_ref_format abstract method

src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/pygit2.py
Codespaces git install appears to be fixed now, both github `/usr/local/bin/git` and system `/usr/bin/git` use `/etc/gitconfig` in the latest codespaces container
Closes https://github.com/iterative/scmrepo/issues/148
=> codespaces: revert config workaround

setup.cfg, src/scmrepo/git/__init__.py, src/scmrepo/git/backend/pygit2.py, tests/test_git.py
implement pygit2 backend for fetch_refspec
fix #168 
Compare to the `cprofile` in https://github.com/iterative/dvc/issues/8477. 
The new greatly reduced the time cost in fetching.
Making the total `dvc exp show` query finished in 1s. And brings a much smoother performance in vs-code extension.  And also solves the hanging problem in https://github.com/iterative/dvc/issues/8762
https://user-images.githubusercontent.com/6745454/212892100-ae2d032d-e23b-4b62-9207-28752a3de4c8.mp4
But we still had one problem remaining to solve, how to make `scmrepo` use the `pygit2` as the default backend. In the test and the demo, I simply raise `NotImplementError` in Dulwich to disable it.
=> implement pygit2 backend for fetch_refspec

src/scmrepo/git/backend/pygit2.py
Because for now `pygit2` fetch didn't support `file://` format on Windows, we removed this prefix. But didn't add it back after the fetch operation finished, and it makes the following `dulwich` backend goes wrong.
So here in the PR, we always create a new remote and delete it after the operation to make the remote config unchanged after the operation. Can be removed after #176 solved.
Related to the CI failure in https://github.com/iterative/dvc/actions/runs/4082287489/jobs/7037469526#logs
=> Solve the url change problem in `pygit2` fetch_refspec

src/scmrepo/git/__init__.py
Using pygit2 was causing https://github.com/iterative/dvc/issues/9080
=> fetch_refspecs: Use `dulwich` for ssh urls.

src/scmrepo/git/backend/dulwich/__init__.py
Otherwise, we may end up leaking lots of open file handles that dulwich keeps open for performance reasons.
See https://github.com/jelmer/dulwich/issues/1155.
=> dulwich: close dulwich repo after clone

src/scmrepo/git/__init__.py
This is raised by gitpython if git's command is not present.
Related https://github.com/iterative/scmrepo/issues/208
=> git: continue trying other backends on GitCommandNotFound

src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/dulwich/asyncssh_vendor.py, tests/test_dulwich.py
Falls back to using `SubprocessSSHVendor` instead of `AsyncSSHVendor` when:
- we are inside git-bash/msys environment on windows
- OpenSSH `~/.ssh/config` exists and contains options which are unsupported by asyncssh
Fixes: https://github.com/iterative/dvc/issues/7702
Related: https://github.com/iterative/dvc-ssh/issues/20
Closes https://github.com/iterative/scmrepo/issues/208
Closes https://github.com/iterative/scmrepo/pull/210
=> dulwich: use `SubprocessSSHVendor` when necessary

pyproject.toml, src/scmrepo/git/backend/base.py, src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/gitpython.py, src/scmrepo/git/backend/pygit2.py, src/scmrepo/git/stash.py, tests/test_stash.py
Closes https://github.com/iterative/scmrepo/issues/211
- Clean workspace on stash.push is now handled properly for all backends
- When checking `is_dirty` or `status`, the check is done within the same backend, which eliminates inconsistencies when mixing status + stash calls across different backends
(This PR does not address the lack of gitattributes support in dulwich)
=> stash: handle clean workspace on push()

pyproject.toml, src/scmrepo/git/backend/dulwich/asyncssh_vendor.py, src/scmrepo/git/backend/dulwich/client.py, src/scmrepo/git/backend/pygit2/callbacks.py
- Adds support for interactive username/password prompt
- Interactive support is disabled when `GIT_TERMINAL_PROMPT` env var is set to `0` (same as CLI Git)
dulwich changes:
- Now follows proper auth workflow for HTTP
1. Unauthenticated request is tried first
2. If request fails, credentials are read from credential helpers and interactive prompt (in that order)
3. Request is retried with credentials from (2), if request fails, we raise the auth error
- asyncssh vendor now supports interactive prompt for username/password when the server requests it
- Note that this is not always available depending on the server
- Github/Gitlab/etc only allow key authentication over SSH
- Mainly only useful for private/self-hosted git over SSH
pygit2 changes:
- Interactive username/pw auth supported for …
=> dulwich/pygit: support interactive username/pw auth

src/scmrepo/git/credentials.py, tests/test_credentials.py
Continuing from https://github.com/iterative/scmrepo/pull/220#issuecomment-1489272094, the issue appears to be from having the cache helper enabled in my git config:
```
[credential]
helper = cache
```
I get the prompt as expected when I disable this. However, when it's enabled, I don't get a prompt, even if I have no credentials cached. For example, this fails:
```
$ git credential-cache exit
$ dvc get -v https://github.com/dberenbaum/config-files vimrc
```
The credential helper does not fail but returns an empty output in this scenario.
I notice we don't have any tests for any of the credential helper logic. Do we need to add something?
I don't mind if you take this over @pmrowla, but once I found the issue it wasn't any extra work to submit the PR.
=> disallow cred helper to return empty output

src/scmrepo/git/backend/dulwich/client.py, src/scmrepo/git/credentials.py, tests/test_credentials.py
see https://github.com/iterative/dvc/issues/9007
- adds support for AWS codecommit credential-helper
=> git.credentials: support UseHttpPath=true for credential helpers

src/scmrepo/git/credentials.py
=> git-credential: disable prompt when not attached to a tty

src/scmrepo/git/credentials.py, tests/test_credentials.py
Currently fails with a config like:
```
[credential]
helper = 
```
I was using that to debug other auth issues by resetting my credential helpers and encountered an error.
=> handle empty credential helper

src/scmrepo/git/credentials.py, tests/test_credentials.py
Fixes https://github.com/iterative/scmrepo/issues/245
=> git.credentials: in/out protocol uses newlines and not os linesep

setup.cfg
pytest-docker deps cannot be pip installed on 3.10+ or on pypy. Issue is with pyyaml<6/Cython install (which comes from pytest-docker): https://github.com/yaml/pyyaml/issues/724
```
Collecting PyYAML<6,>=3.10 (from docker-compose<2.0,>=1.27.3->pytest-docker==0.12.0->scmrepo==1.0.5.dev4+gd3f663a)
```
see: https://github.com/iterative/scmrepo/actions/runs/5596450156/jobs/10233487390?pr=252
=> temporarily disable pytest-docker entirely on py<3.10

src/scmrepo/git/backend/dulwich/asyncssh_vendor.py
Closes https://github.com/iterative/dvc/issues/9737
- Makes scmrepo behave the same as git when prompting for a passphrase
```
$ dvc import git@github.com:pmrowla/test-dvc-private.git data/data.xml
Importing 'data/data.xml (git@github.com:pmrowla/test-dvc-private.git)' -> 'data.xml'
Cloning test-dvc-private.git|                             |0.00/? [00:00,      ?obj/s]
Enter passphrase for key '~/git/scratch/test-ssh-passphrase/id_ed25519':
To track the changes with git, run:
git add data.xml.dvc
To enable auto staging, run:
dvc config core.autostage true
```
=> dulwich: support interactive SSH key passphrase prompt in asyncssh vendor

src/scmrepo/git/__init__.py, src/scmrepo/git/backend/base.py, src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/gitpython.py, src/scmrepo/git/backend/pygit2/__init__.py, src/scmrepo/git/objects.py, tests/test_git.py, tests/test_pygit2.py
Implements `git tag -a` support in all of our backends (required for GTO).
=> git: support reading/writing annotated tags

src/scmrepo/git/backend/pygit2/__init__.py, tests/test_pygit2.py
Fixes https://github.com/iterative/studio/issues/7185
PyGit2 (and our backend in scmrepo) throws an exception if there is no Git config set. Might be related to this https://github.com/libgit2/libgit2/issues/1528
Here we are trying to get env vars first, if they are specified and don't fail fast on the default signature call.
=> feat(pygit2): author and committer don't break if env is set and git conf is not

.github/workflows/tests.yaml, noxfile.py, setup.cfg, src/scmrepo/git/backend/pygit2/__init__.py
Closes #258 
Also drops pypy testing in CI as pygit2 1.13.0 no longer builds wheels for pypy.
=> pygit: use anonymous remotes

pyproject.toml, setup.cfg, src/scmrepo/base.py, src/scmrepo/fs.py, src/scmrepo/git/__init__.py, src/scmrepo/git/backend/base.py, src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/gitpython.py, src/scmrepo/git/backend/pygit2/__init__.py, src/scmrepo/git/backend/pygit2/filter.py, src/scmrepo/git/config.py, src/scmrepo/git/lfs/__init__.py, src/scmrepo/git/lfs/client.py, src/scmrepo/git/lfs/exceptions.py, src/scmrepo/git/lfs/fetch.py, src/scmrepo/git/lfs/object.py, src/scmrepo/git/lfs/pointer.py, src/scmrepo/git/lfs/progress.py, src/scmrepo/git/lfs/smudge.py, src/scmrepo/git/lfs/storage.py, src/scmrepo/git/objects.py, tests/test_fs.py, tests/test_git.py, tests/test_lfs.py
Will close https://github.com/iterative/dvc/issues/9175
Requires https://github.com/libgit2/pygit2/pull/1237
- Adds minimal read-only LFS implementation
- `lfs smudge` filtering is enabled by via libgit2/pygit2 backend filter
- When Git checks out (or reads) a blob with the `filter=lfs` .gitattribute the LFS object will be read from local storage or fetched (per default CLI `lfs smudge` behavior)
- `lfs fetch` is implemented via `scmrepo.git.lfs.fetch` and can be used to fetch multiple LFS objects in a batch operation (so subsequent git checkout/blob read can be done from local storage)
- Minimal CLI implementation is available for some commands. This is mainly useful for compatibility testing purposes and should not be considered a complete replacement for CLI LFS, commands only …
=> support LFS smudge (read operations)

src/scmrepo/git/lfs/client.py
I've fixed the download of LFS objects when the [Batch API](https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md) response does not contain a `transfer` property. In this case, the `transfer` property should default to `"basic"`. This [behavior conforms with the spec](https://github.com/git-lfs/git-lfs/blob/ad64c6cf4e40688ba64e2026e5eb21b845a288b1/docs/api/basic-transfers.md?plain=1#L7-L9):
> All Git LFS clients and servers SHOULD support it, and default to it if the [Batch API](https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md) request or response do not specify a `transfer` property.
For instance, GitLab's LFS server does not provide the `transfer` property, which causes `scmrepo` to fail with:
```
.../scmrepo/git/lfs/client.py", line 201, in _download
raise …
```
=> lfs: default to basic transfer API

src/scmrepo/git/lfs/client.py
Some minor cleanup: I've removed the [unused](https://github.com/search?q=repo%3Aiterative%2Fscmrepo%20%22_LFSClient%22&type=code) `_LFSClient` class.
=> lfs: remove unused `_LFSClient` class

src/scmrepo/git/lfs/client.py
Just some minor cleanup: I've removed the obsolete class constructor of `_LFSFileSystem`. It simply calls the parent class constructor and passes all arguments through, so there's no need to have it.
=> lfs: remove obsolete class constructor

src/scmrepo/git/lfs/client.py
Some more cleanup: I've removed the obsolete [`_LFSFileSystem.get_client()`](https://github.com/iterative/scmrepo/blob/f5df02ac4d16358b68c99b639fe048098ebb5e19/src/scmrepo/git/lfs/client.py#L36-L67) method override. It's logically identical with its [upstream implementation in `dvc-http` v2.30.2](https://github.com/iterative/dvc-http/blob/2.30.2/dvc_http/__init__.py#L94-L127) (which is the last release before some minor code changes)
```diff
async def get_client(self, **kwargs):
+        import aiohttp
from aiohttp_retry import ExponentialRetry
-        from dvc_http import make_context
+
+        from .retry import ReadOnlyRetryClient
kwargs["retry_options"] = ExponentialRetry(
attempts=self.SESSION_RETRIES,
```
and also with its [upstream implementation in `dvc-http`'s current state of …
=> lfs: remove obsolete `_LFSFileSystem.get_client()` method override

src/scmrepo/git/lfs/client.py
I've fixed the Batch API request header to include `Accept: application/vnd.git-lfs+json` as stated in the [spec](https://github.com/git-lfs/git-lfs/blob/b4a0927e399ed4acfa838b0c3c17011dce1658ae/docs/api/batch.md#L19):
> All Batch API requests use the POST verb, and require the following HTTP headers. The request and response bodies are JSON.
>
> ```
> Accept: application/vnd.git-lfs+json
> Content-Type: application/vnd.git-lfs+json
> ```
For instance, omitting this header leads to an error when fetching LFS objects from github.com:
```console
$ dvc import https://github.com/githubschool/lfs-example TogglDesktop-7_4_373.dmg
Importing 'TogglDesktop-7_4_373.dmg (https://github.com/githubschool/lfs-example)' -> 'TogglDesktop-7_4_373.dmg'
...
Could not open LFS object, falling back to raw …
```
=> lfs: add missing `Accept` header to Batch API request

.github/workflows/tests.yaml, CONTRIBUTING.rst, noxfile.py, pyproject.toml, src/scmrepo/asyn.py, src/scmrepo/fs.py, src/scmrepo/git/__init__.py, src/scmrepo/git/backend/base.py, src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/dulwich/asyncssh_vendor.py, src/scmrepo/git/backend/dulwich/client.py, src/scmrepo/git/backend/gitpython.py, src/scmrepo/git/backend/pygit2/__init__.py, src/scmrepo/git/backend/pygit2/callbacks.py, src/scmrepo/git/backend/pygit2/filter.py, src/scmrepo/git/config.py, src/scmrepo/git/credentials.py, src/scmrepo/git/lfs/client.py, src/scmrepo/git/lfs/fetch.py, src/scmrepo/git/lfs/object.py, src/scmrepo/git/lfs/pointer.py, src/scmrepo/git/lfs/progress.py, src/scmrepo/git/lfs/storage.py, src/scmrepo/git/objects.py, tests/conftest.py, tests/test_dulwich.py, tests/test_git.py, tests/test_scmrepo.py
* https://github.com/libgit2/pygit2/pull/1259
=> pygit2: bump to 1.14.0

src/scmrepo/git/backend/pygit2/__init__.py, src/scmrepo/git/backend/pygit2/callbacks.py
=> pygit2: support 1.14 credentials

pyproject.toml, src/scmrepo/git/lfs/client.py
I've refactored the `LFSClient` class some more to directly use `fsspec`'s `HTTPFileSystem` implementation instead of the one from `dvc-http`, as most of `dvc-http`'s implementation is irrelevant to making HTTP requests independent of DVC. I've retained the retry client, which `dvc-http` also uses, because that's generally consistent with the official Git LFS client's implementation. In fact, the [official Git LFS client also supports retries for Batch API requests](https://github.com/git-lfs/git-lfs/blob/82f58ad228ff49abb31618152b1992820bb84f5e/tq/api.go#L94), which are disabled by `dvc-http`'s `ReadOnlyRetryClient` class. To otherwise keep the retry behavior as before, I've [copied the retry settings from `dvc-http`](https://github.com/iterative/dvc-http/blob/1df9de067248c9408b5e8b24c53c …
=> lfs: use `HTTPFileSystem` from `fsspec` instead of `dvc-http`

pyproject.toml, src/scmrepo/git/lfs/client.py, src/scmrepo/git/lfs/progress.py, src/scmrepo/git/lfs/smudge.py, src/scmrepo/git/lfs/storage.py
- Drops dvc-objects usage in favor of fsspec equivalents
- Drops DVC jobs/_JOBS usage in favor of exposing fsspec batch_size (see https://github.com/iterative/scmrepo/pull/315#issuecomment-1928855658)
=> lfs: drop dvc objects dependency

src/scmrepo/git/backend/dulwich/__init__.py
Closes #321.
I am not sure how I will use this in `dvc`, but I created this API so that I can play with it.
=> dulwich: add ls-remote to list remote repository

src/scmrepo/git/lfs/client.py
I've added support for Git SSH URLs to the Git LFS client. Resolves #288.
I've refactored the `LFSClient` class a little to have the common code in `LFSClient` and implement logic specific to Git HTTP URLs and Git SSH URLs in subclasses. The `LFSClient` class is now abstract with one abstract method `_get_auth_header(upload: bool): dict` which gets implemented by the private subclasses `_HTTPLFSClient` and `_SSHLFSClient`. `_HTTPLFSClient` retrieves credentials as before using the credential helper, but instead of using AIOHTTP's `auth` argument, it creates the basic auth header manually using `BasicAuth(...).encode()` which gets passed along with other headers. `_SSHLFSClient` retrieves credentials using `ssh git@<host> <project_path> upload|download` (as documented in the [Git LFS SSH …
=> lfs: add support for Git SSH URLs

pyproject.toml
Hopefully that workaround is not needed anymore and we could use it on all Python versions
=> chore(deps): cleanup and bump pytest docker

src/scmrepo/git/lfs/client.py
I've added support for handling rate limit responses and retrying requests accordingly.
Typical rate limit responses use the status code 429 and include one of the following headers:
* `Retry-After: <delay in seconds>` is used by, e.g., GitLab
* `RateLimit-Reset: <timestamp>` is used by, e.g., GitLab
* `X-RateLimit-Reset: <timestamp>` is used by, e.g., GitHub
The implementation is inspired by the [corresponding implementation in the `python-gitlab` library](https://github.com/python-gitlab/python-gitlab/blob/14a3ffe4cc161be51a39c204350b5cd45c602335/gitlab/client.py#L764-L775) and based on the [GitHub documentation on rate limits](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#checking-the-status-of-your-rate-limit).
=> lfs: add support for rate limit retries

pyproject.toml, src/scmrepo/git/lfs/client.py, tests/test_lfs.py
I've added some tests for rate limit retries.
Follow-up of #340.
/cc @shcheklein
=> lfs: add tests for rate limit retries

src/scmrepo/git/backend/pygit2/__init__.py, src/scmrepo/git/lfs/client.py, src/scmrepo/urls.py, tests/test_pygit2.py, tests/test_urls.py
See discussion: https://discuss.dvc.org/t/dvc-import-fails-with-git-failed-to-fetch-ref-from/1997
scp shorthand URL format is as follows:
```console
[user@]host.domain.com:path/to/resource
```
So, `user` can be anything, and is optional. 
> [!NOTE]
> Does not work with absolute paths in scp-style URLs, eg: `git@github.com:/path/to/resource`.
=> support scp-style shorthand urls with users other than git@

src/scmrepo/git/lfs/fetch.py
I've optimized LFS path filtering as we discussed in #338. The first optimization implements the suggestion in https://github.com/iterative/scmrepo/issues/338#issuecomment-2081256097 to short-cut a single-path `include` filter. Here are the tests for the regex that extracts the path prefix: https://regex101.com/r/wBjHf0/1 Note that the extra `\n` on regex101.com is only necessary to allow one test case per line, it isn't needed in the actual regex. ~~The second optimization unionizes the filename regex patterns derived from Unix filename patterns and matches each path against the pre-compiled single regex, which is faster than matching against the Unix filename patterns individually. Also, it avoids intermediate list materialization but instead implements a streaming filter.~~
~~As the …
=> lfs: optimize path filtering

noxfile.py, src/scmrepo/git/backend/pygit2/__init__.py
Fixes https://github.com/iterative/dvc/issues/10431
Relevant changelog https://github.com/libgit2/pygit2/compare/v1.14.1...v1.15.0#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed
=> Fix pygit2 latest update compatibility

.github/workflows/tests.yaml, noxfile.py
GitHub has dependency alerts and dependency security updates that can replace `safety`.
For the past few months, safety has been raising vulnerability errors for `pip` and now `jinja2`. The latter is a dependency of `safety` itself, and both CVEs are disputed.
Which is breaking CI for us.
=> drop safety

src/scmrepo/git/backend/dulwich/asyncssh_vendor.py, tests/test_dulwich.py
Empty passwords were being passed as `()` instead of `None` to asyncssh, causing unexpected failure.
See https://discuss.dvc.org/t/error-in-pushing-experiments/2138 and the added test for how to reproduce it.
In https://github.com/ronf/asyncssh/blob/050e5c1a0f42d5f145b44c33b183ff745447a687/asyncssh/connection.py#L7790, you can see that `username` defaults to `()`, but `password` defaults to `None`.
=> Handle missing password

src/scmrepo/git/backend/dulwich/asyncssh_vendor.py
See https://discuss.dvc.org/t/dvc-exp-push-fails-with-error-unexpected-error-interactivesshclient-object-has-no-attribute-passphrases/2187
=> fix InteractiveSSHClient _passphrases attr

.gitignore, pyproject.toml, src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/pygit2/__init__.py, tests/test_git.py
Fixes https://github.com/iterative/dvc/issues/10563
+ a few other occurrences in dulwich
=> pass and init proxy settings in dulwich and pygit2

src/scmrepo/git/credentials.py, tests/test_credentials.py
Fixes #391
Fix handling of osxkeychain addtional keys (#391) 
* git-credential-helper v2.45 < v2.47.0 can output additional garbage bytes after the username. 
* git-credential-helper >= v2.46.0 outputs additional `capability[]` and `state` keys.
=> Fix handling of osxkeychain addtional keys (#391)

src/scmrepo/fs.py
This method was a temporary workaround. The issue was fixed and released in fsspec==2023.3.0, and we are currently requiring fsspec==2024.2.0.
=> fs: remove unnecessary get_file method

src/scmrepo/git/backend/dulwich/asyncssh_vendor.py, tests/test_dulwich.py
Looks like this is no longer necessary, GitHub seems to return proper algorithm name these days, at least it does for me.
I tried with the following script:
```python
import asyncio
from asyncssh import ProtocolError, connect
from asyncssh.auth import MSG_USERAUTH_PK_OK, _ClientPublicKeyAuth
def _process(self, _pkttype, _pktid, packet):
algorithm = packet.get_string()
key_data = packet.get_string()
packet.check_end()
print(algorithm, self._keypair.algorithm)
if algorithm != self._keypair.algorithm or key_data != self._keypair.public_data:
raise ProtocolError("Key mismatch")
self.create_task(self._send_signed_request())
return True
_ClientPublicKeyAuth._packet_handlers[MSG_USERAUTH_PK_OK] = _process
async def func():
async with connect(host="github.com", username="git", known_hosts=None): …
```
=> remove asyncssh patching

src/scmrepo/asyn.py, tests/test_git.py
Mind: it goes on top of the `pre-commit-ci-update-config` branch / PR that has also some mypy fixes, but fails bc of these issues:
Fixes https://github.com/iterative/scmrepo/issues/422
Fixes https://github.com/iterative/dvc/issues/10807
Context https://github.com/fsspec/filesystem_spec/issues/1861
There is a separate issue with gitignore test (regression in dulwich?), but let's unblock the repo first - too many issues at once ...
=> Remove async selector policy after fsspec

src/scmrepo/base.py, src/scmrepo/git/__init__.py, src/scmrepo/git/backend/dulwich/__init__.py, src/scmrepo/git/backend/gitpython.py, src/scmrepo/git/backend/pygit2/__init__.py
`git` doesn't add files from submodules when staging, so we align `dulwich` with that behavior.
Also, `libgit2`/`pygit2` removes files from submodules on `reset()`, so raise `NotImplementedError` for now to avoid accidental deletions, and redirect such cases to the `GitPython` backend instead.
Fixes https://github.com/iterative/dvc/issues/10823.
=> dulwich: do not add files from submodules
